services:
  server:
    container_name: "squealer-app"
    volumes:
      - .:/app
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: